esphome:
  name: boiler-temperature-monitor

packages:
  esp32: !include shared-nodemcu-32.yaml
  wifi: !include shared-wifi.yaml

<<: !include shared.yaml
<<: !include default-sensors.yaml

dallas:
  - pin: 23

sensor:
  - platform: dallas
    address: "0x9a00000015b6a628"
    name: "Radiator Flow Temperature"

