# A set of default ESP32 sensors to include with any node.

sensor:
  - platform: wifi_signal
    name: "Node WiFi Signal Strength"
    update_interval: 60s

  - platform: uptime
    name: "Node Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "Node Temperature"

text_sensor:
  - platform: version
    name: "Node ESPHome Version"

  - platform: wifi_info
    ip_address:
      name: "Node IP Address"
